namespace Origo.Bifrost.Warehouse;

codeunit 10078427 "Whse Putaway Register Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Warehouse.Putaway.Register - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Registers a Warehouse Put-away. Wraps BC codeunit 7307 `Whse.-Activity-Register` (the same codeunit used for Pick registration). After registration the bin contents are updated (stock moves from the receive bin to the storage bin), the put-away header is deleted and a row appears in `Registered Whse. Activity Hdr.`, and the source Posted Whse. Receipt Line''s `Qty. Put Away` is incremented.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound (state change)  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Posting Gate');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Requires the `BIFROST WhsePost ori` permission set on the message-task user. Without it the request returns an Error response and nothing is registered.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Identifying the Warehouse Put-away');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Provide the put-away via the Bifrost Subject (GUID = SystemId of the activity header, or text = `No.`) or via one of these request JSON keys:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Key | Meaning |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `systemId` / `recordSystemId` / `id` | SystemId of the `Warehouse Activity Header` (Type = Put-away). |');
        HelpBuilder.AppendLine('| `putawayNo` / `no` | `No.` of the `Warehouse Activity Header` (Type = Put-away). |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Pre-condition: Lines Must Have Qty. to Handle');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('BC registers only what the warehouse worker has confirmed put away. By default `Warehouse.Putaway.Create` populates `Qty. to Handle` on every line (the `doNotFillQtyToHandle = false` default of the BC report). If you call `Warehouse.Putaway.Register` against a put-away with zero `Qty. to Handle` on every line, BC raises `Nothing to register.`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('To register a partial put-away, first call `Data.Records.Set` on `Warehouse Activity Line` to update `Qty. to Handle` per line. On `Bin Mandatory` / `Directed Put-away and Pick` locations put-away lines come in **Take + Place pairs** — update both rows to the same value. On a **non-bin** location (`Bin Mandatory = false`) there is a single line per source line and no pairing (verified live: a 1-line receipt produced 1 put-away line).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Parameter | Type | Required | Notes |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| `putawayNo` | code[20] | One identifier required | Or use `no` / `systemId` / Subject. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{ "putawayNo": "WPA000456" }');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Verified live (BC 27, CRONUS IS) — registering put-away `PU000025` (1 line, 5 × item `1896-S`) created from Posted Whse. Receipt `R_000030`:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "putawayNo": "PU000025",');
        HelpBuilder.AppendLine('  "linesRegistered": 1,');
        HelpBuilder.AppendLine('  "totalQtyRegistered": 5,');
        HelpBuilder.AppendLine('  "postedWhseReceiptNo": "R_000030",');
        HelpBuilder.AppendLine('  "postedWhseReceiptSystemId": "26cfe041-ff61-f111-b7a5-fb5809e04ea8",');
        HelpBuilder.AppendLine('  "registeredPutawayNo": "PU_000007",');
        HelpBuilder.AppendLine('  "registeredPutawaySystemId": "244cf98f-ff61-f111-b7a5-fb5809e04ea8",');
        HelpBuilder.AppendLine('  "receiptLines": [');
        HelpBuilder.AppendLine('    {');
        HelpBuilder.AppendLine('      "postedWhseReceiptNo": "R_000030",');
        HelpBuilder.AppendLine('      "lineNo": 10000,');
        HelpBuilder.AppendLine('      "sourceDocument": "Purchase Order",');
        HelpBuilder.AppendLine('      "sourceNo": "106032",');
        HelpBuilder.AppendLine('      "sourceLineNo": 10000,');
        HelpBuilder.AppendLine('      "itemNo": "1896-S",');
        HelpBuilder.AppendLine('      "qty": 5,');
        HelpBuilder.AppendLine('      "qtyPutAway": 5,');
        HelpBuilder.AppendLine('      "qtyOutstanding": 0,');
        HelpBuilder.AppendLine('      "status": "Completely Put Away"');
        HelpBuilder.AppendLine('    }');
        HelpBuilder.AppendLine('  ],');
        HelpBuilder.AppendLine('  "message": "Warehouse Put-away PU000025 (1 lines) registered against Posted Whse. Receipt R_000030."');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('`qtyPutAway` and `status` on each receipt line reflect the post-registration totals: full registrations transition the line to `Completely Put Away`; partial registrations leave the line at `Partially Put Away` (`Qty. Outstanding > 0`).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Field Restrictions');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('None — this message type does not accept any caller-supplied field overrides.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `Warehouse Activity Header identifier is missing. Pass it as the subject, or as one of: systemId, recordSystemId, id, putawayNo, no.` (`MissingParameter`) | No identifier in `subject` or the request JSON. |');
        HelpBuilder.AppendLine('| `Warehouse Activity Header "{value}" was not found (from {subject or key}).` (`RecordNotFound`) | An identifier was given but matches no record; `parameter` and `received` name it. Every identifier supplied is tried. |');
        HelpBuilder.AppendLine('| `The identifiers in {a} and {b} point to different records.` (`ConflictingIdentifiers`) | Two identifiers were given that resolve to different records. |');
        HelpBuilder.AppendLine('| `Warehouse Activity {n} is not of Type Put-away.` | Activity exists but is a Pick / Movement / Invt. Put-away. |');
        HelpBuilder.AppendLine('| `Warehouse Put-away {n} has no lines.` | Header exists with zero lines (shouldn''t happen for put-aways created by BC). |');
        HelpBuilder.AppendLine('| `Nothing to register.` | All lines have `Qty. to Handle = 0`. |');
        HelpBuilder.AppendLine('| `Posting denied: missing ''BIFROST WhsePost ori'' permission set.` | Caller lacks the warehouse posting permission. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Pitfalls');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- **Put-away header disappears after registration**: On `Success` the `Warehouse Activity Header` row is deleted and a `Registered Whse. Activity Hdr.` row appears. A second `Warehouse.Putaway.Register` call against the same `putawayNo` therefore returns `RecordNotFound` (`Warehouse Activity Header "{n}" was not found (from putawayNo).`) — that is the success indicator, not a failure. Read the history via `Data.Records.Get` on `Registered Whse. Activity Hdr.` (filter by `Whse. Activity No.`).');
        HelpBuilder.AppendLine('- **Activity Type filter**: `Warehouse Activity Header` is shared by Picks, Put-aways, Movements, and Invt. Put-aways. The wrapper checks `Type = Put-away` and rejects others — but make sure the `putawayNo` / SystemId you supply is genuinely a Put-away.');
        HelpBuilder.AppendLine('- **Partial put-aways need `Data.Records.Set` first**: BC fills `Qty. to Handle` automatically when the put-away is created. If the warehouse worker placed less, update each line''s `Qty. to Handle` via `Data.Records.Set` on `Warehouse Activity Line` (primaryKey = `Activity Type`, `No.`, `Line No.`) before calling Register. Zero `Qty. to Handle` across all lines yields `Nothing to register.`');
        HelpBuilder.AppendLine('- **Take and Place lines (bin locations only)**: On `Bin Mandatory` / `Directed Put-away and Pick` locations BC put-away lines come in pairs — one `Action Type = Take` (from the receive bin) and one `Action Type = Place` (to the storage bin) per source line. When updating `Qty. to Handle`, update **both** rows to the same value or BC rejects the register with `Qty. to Handle (Base) in the line must be equal to ...`. Non-bin locations have a single line per source line with no Take/Place split.');
        HelpBuilder.AppendLine('- **Bin contents update**: Registration credits the storage bin and debits the receive bin via `Whse. Item Tracking` and `Bin Content`. Subsequent picks for the same item will pull from the new storage bin.');
        HelpBuilder.AppendLine('- **Posting gate**: The message-task user must have `BIFROST WhsePost ori` even though no item ledger entries are produced by put-away registration — BC still treats it as a warehouse posting action.');
        HelpBuilder.AppendLine('- **Source Posted Receipt status**: A partially registered put-away leaves the Posted Whse. Receipt Line at `Partially Put Away`. A second `Warehouse.Putaway.Create` against the same Posted Receipt then generates a new put-away for the outstanding quantity.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## AI-Agent Guidance');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('When orchestrating this message type from an agent:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. **Every identifier sent is tried**: `subject`, `systemId`, `recordSystemId`, `id`, `putawayNo` and `no`. Two that point to different activities give `ConflictingIdentifiers`; send one.');
        HelpBuilder.AppendLine('2. **Capture `registeredPutawaySystemId` from the response** if you need to navigate to the history record afterwards — re-deriving it from `putawayNo` after registration requires a `Registered Whse. Activity Hdr.` lookup keyed on `Whse. Activity No.`.');
        HelpBuilder.AppendLine('3. **Treat `RecordNotFound` on a known put-away as evidence the put-away was already registered** (the activity header moved to history). Confirm by reading `Registered Whse. Activity Hdr.` before retrying.');
        HelpBuilder.AppendLine('4. **Idempotency**: This message type is **not** idempotent — second successful invocation against the same `putawayNo` is impossible because the header is gone. Use `Registered Whse. Activity Hdr.` to check whether registration already happened.');
        HelpBuilder.AppendLine('5. **Workflow completion**: On `Success` against the last outstanding line of a Posted Whse. Receipt, the Posted Receipt Line transitions to `Completely Put Away` and the inbound flow is complete. The response includes `postedWhseReceiptNo` and `postedWhseReceiptSystemId` for downstream queries.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Workflow Chain');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. `Sales.ReturnOrder.Release` (or Purchase Order release)');
        HelpBuilder.AppendLine('2. `Warehouse.Receipt.Create`');
        HelpBuilder.AppendLine('3. `Warehouse.Receipt.Post`');
        HelpBuilder.AppendLine('4. `Warehouse.Putaway.Create`');
        HelpBuilder.AppendLine('5. **`Warehouse.Putaway.Register`** — this message type');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse.Putaway.Create` — produces the input.');
        HelpBuilder.AppendLine('- `Data.Records.Set` on `Warehouse Activity Line` — to adjust `Qty. to Handle` before registering a partial put-away.');
        HelpBuilder.AppendLine('- `Data.Records.Get` — load any field on the resulting `Registered Whse. Activity Hdr.` / `Registered Whse. Activity Line` or on the source `Posted Whse. Receipt Line`.');

        HelpText := HelpBuilder.ToText();
    end;
}
