namespace Origo.Bifrost.Warehouse;

codeunit 10078426 "Whse Putaway Create Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Warehouse.Putaway.Create - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Ensures a Warehouse Put-away exists for an existing Posted Whse. Receipt and returns it. Wraps BC report 7305 `Whse.-Source - Create Document` (the same action invoked by *Create Put-away* on the Posted Warehouse Receipt page) with `SetPostedWhseReceiptLine`. The resulting `Warehouse Activity Header` (`Type = Put-away`) is returned along with line totals.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('The message type is **idempotent for the already-created case**: if a put-away already exists for the receipt (most commonly because posting auto-created it — see below), the existing put-away is returned with `"alreadyExisted": true` instead of an error.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound (state change)  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Worksheet vs. auto-create — read this first');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Whether posting a Warehouse Receipt **auto-creates** the put-away is the single most important thing to understand about this message type. Base app codeunit 5760 `Whse.-Post Receipt` computes:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('ShouldCreatePutAway := "Require Put-away" AND NOT "Use Put-away Worksheet"');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Location setup | Posting the receipt… | `Warehouse.Putaway.Create` then… |');
        HelpBuilder.AppendLine('|---|---|---|');
        HelpBuilder.AppendLine('| `Require Put-away = true`, `Use Put-away Worksheet = false` (BC default, e.g. demo locations GULUR / HVÍTUR) | **auto-creates** the put-away | finds report 7305 has nothing left, recovers, and returns the auto-created put-away with `alreadyExisted = true`. |');
        HelpBuilder.AppendLine('| `Require Put-away = true`, `Use Put-away Worksheet = true` | does **not** create a put-away (work is left for the worksheet) | creates the put-away fresh and returns `alreadyExisted = false`. |');
        HelpBuilder.AppendLine('| `Require Put-away = false` | places stock directly into inventory | no put-away is possible — returns `No Warehouse Put-away was created for ...`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('So on a standard Require-Put-away location the put-away you receive back was created **by posting**, not by this call. That is expected and correct — chain straight to `Warehouse.Putaway.Register`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Prerequisites');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- A **Posted** Whse. Receipt must exist for the source. Unposted Warehouse Receipts cannot be used — call `Warehouse.Receipt.Post` first.');
        HelpBuilder.AppendLine('- The receipt''s `Location Code` must point to a Location with `Require Put-away = true`.');
        HelpBuilder.AppendLine('- At least one Posted Whse. Receipt Line must still have `Status <> Completely Put Away` and `Quantity > 0`. (Once everything is put away you get `... has no lines to put away.`)');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Identifying the Posted Whse. Receipt');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Provide the posted receipt via the Bifrost Subject (GUID = SystemId, or text = `No.`) or via one of these request JSON keys:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Key | Meaning |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `systemId` / `recordSystemId` / `id` | SystemId of the `Posted Whse. Receipt Header`. |');
        HelpBuilder.AppendLine('| `postedWhseReceiptNo` / `receiptNo` / `no` | `No.` of the `Posted Whse. Receipt Header`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Parameter | Type | Required | Notes |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| `postedWhseReceiptNo` | code[20] | One identifier required | Or use `receiptNo` / `no` / `systemId` / Subject. |');
        HelpBuilder.AppendLine('| `assignedUserId` | code[50] | No | Applied to the put-away header (created or pre-existing). Subject to write-restriction on `Warehouse Activity Header."Assigned User ID"`. The user must be a `Warehouse Employee` at the put-away''s location. |');
        HelpBuilder.AppendLine('| `sortingMethod` | string | No | Case-insensitive name from BC enum `Whse. Activity Sorting Method`. Verified live (BC 27): `None`, `Item`, `Document`, `Shelf or Bin`, `Due Date`, `Ship-To`, `Bin Ranking`, `Action Type`. The error response lists the exact set valid on your build. Subject to write-restriction on `Warehouse Activity Header."Sorting Method"`. |');
        HelpBuilder.AppendLine('| `setBreakbulkFilter` | boolean | No (default false) | Not supported in this API version. Sending `true` returns an error. |');
        HelpBuilder.AppendLine('| `doNotFillQtyToHandle` | boolean | No (default false) | Not supported in this API version. Sending `true` returns an error. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "postedWhseReceiptNo": "R_000030",');
        HelpBuilder.AppendLine('  "assignedUserId": "ADMIN",');
        HelpBuilder.AppendLine('  "sortingMethod": "Bin Ranking"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Verified live (BC 27, CRONUS IS, location `CEPUT` with `Use Put-away Worksheet = true`, PO of 5 × item `1896-S`):');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "postedWhseReceiptNo": "R_000030",');
        HelpBuilder.AppendLine('  "postedWhseReceiptSystemId": "26cfe041-ff61-f111-b7a5-fb5809e04ea8",');
        HelpBuilder.AppendLine('  "putawayNo": "PU000025",');
        HelpBuilder.AppendLine('  "putawaySystemId": "31cfe041-ff61-f111-b7a5-fb5809e04ea8",');
        HelpBuilder.AppendLine('  "locationCode": "CEPUT",');
        HelpBuilder.AppendLine('  "assignedUserId": "",');
        HelpBuilder.AppendLine('  "sortingMethod": "None",');
        HelpBuilder.AppendLine('  "alreadyExisted": false,');
        HelpBuilder.AppendLine('  "totalPutawayLines": 1,');
        HelpBuilder.AppendLine('  "totalQtyToHandle": 5,');
        HelpBuilder.AppendLine('  "message": "Warehouse Put-away PU000025 created from Posted Receipt R_000030 with 1 lines."');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `alreadyExisted` — `false` when this call created the put-away; `true` when an open put-away already existed (e.g. posting auto-created it) and was returned as-is.');
        HelpBuilder.AppendLine('- `totalPutawayLines` — on a **non-bin** location (`Bin Mandatory = false`) there is **one** put-away line per source line (verified: 1 line for a single-line receipt). On `Bin Mandatory` / `Directed Put-away and Pick` locations each source line becomes a **Take + Place pair**, so the count is roughly double.');
        HelpBuilder.AppendLine('- When no `sortingMethod` is supplied, the response returns `"sortingMethod": "None"` (the BC enum''s blank/whitespace caption is normalised to `None`).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Verified Behaviour Matrix');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Each row was executed live via the BC Bifrost MCP `invoke_message_type` tool:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Scenario | Result |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| Worksheet location, fresh receipt | `Success`, `alreadyExisted = false`, put-away created. |');
        HelpBuilder.AppendLine('| Non-worksheet location (posting auto-created) | `Success`, `alreadyExisted = true`, auto-created put-away returned. |');
        HelpBuilder.AppendLine('| Call again while an open put-away exists | `Success`, `alreadyExisted = true` (same put-away). |');
        HelpBuilder.AppendLine('| Call after the receipt is fully put away | Error `Posted Whse. Receipt {n} has no lines to put away.` |');
        HelpBuilder.AppendLine('| `sortingMethod = "NotAMethod"` | Error `sortingMethod ''NotAMethod'' is not valid. Expected one of: None, Item, ...` |');
        HelpBuilder.AppendLine('| No identifier | Error `Posted Whse. Receipt Header identifier is missing. ...` (`MissingParameter`) |');
        HelpBuilder.AppendLine('| Unknown receipt | Error `Posted Whse. Receipt Header "{value}" was not found (from {subject or key}).` (`RecordNotFound`) |');
        HelpBuilder.AppendLine('| `setBreakbulkFilter = true` | Error `setBreakbulkFilter = true is not supported by this API version. ...` |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Posting Gate');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('None — put-away creation does not register stock movement. The companion `Warehouse.Putaway.Register` requires the `BIFROST WhsePost ori` permission set.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Field Restrictions');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Before applying caller-supplied values to the put-away, the implementation calls `Bifrost Field Access.IsFieldWriteRestricted` on:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse Activity Header."Assigned User ID"` (when `assignedUserId` is supplied)');
        HelpBuilder.AppendLine('- `Warehouse Activity Header."Sorting Method"` (when `sortingMethod` is supplied)');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('A restricted field aborts the request with an Error response — the put-away still exists on disk; remove or rerun without the restricted parameter.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `Posted Whse. Receipt Header identifier is missing. Pass it as the subject, or as one of: systemId, recordSystemId, id, postedWhseReceiptNo, receiptNo, no.` (`MissingParameter`) | No identifier in `subject` or the request JSON. |');
        HelpBuilder.AppendLine('| `Posted Whse. Receipt Header "{value}" was not found (from {subject or key}).` (`RecordNotFound`) | An identifier was given but matches no record; `parameter` and `received` name it. Every identifier supplied is tried. |');
        HelpBuilder.AppendLine('| `The identifiers in {a} and {b} point to different records.` (`ConflictingIdentifiers`) | Two identifiers were given that resolve to different records. |');
        HelpBuilder.AppendLine('| `Posted Whse. Receipt {n} has no lines to put away.` | Header exists but every line is `Completely Put Away` or has `Quantity = 0`. |');
        HelpBuilder.AppendLine('| `sortingMethod ''{x}'' is not valid. Expected one of: ...` | Value not in `Whse. Activity Sorting Method.Names()`. |');
        HelpBuilder.AppendLine('| `Field {n} is restricted for write on table {t}.` | `Bifrost Field Access` blocks `assignedUserId` or `sortingMethod`. |');
        HelpBuilder.AppendLine('| `... = true is not supported by this API version.` | `setBreakbulkFilter` or `doNotFillQtyToHandle` supplied as `true`. |');
        HelpBuilder.AppendLine('| `No Warehouse Put-away was created for ...` | Report 7305 ran without error but produced no header AND none pre-existed — e.g. the location does not actually require put-away, or stock was cross-docked. |');
        HelpBuilder.AppendLine('| (bin errors, verbatim from BC) | On `Bin Mandatory` / directed locations with no resolvable destination bin: e.g. `There is no Bin ...`. Surfaced unchanged. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('> Note: `There is nothing to handle.` (raised by report 7305 when a put-away already exists) is **no longer surfaced as an error** — the implementation detects the existing put-away and returns it with `alreadyExisted = true`. You will only see that text if the receipt has a put-away on disk that the wrapper somehow cannot match (it should not happen for put-aways created by BC).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Pitfalls');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- **Put-away source is POSTED, not unposted**: A Warehouse Receipt must be posted (via `Warehouse.Receipt.Post`) before a put-away can be created. The unposted `Warehouse Receipt Header` cannot drive put-away creation.');
        HelpBuilder.AppendLine('- **The put-away is usually created by posting, not by this call**: On any `Require Put-away` location that is not a worksheet location, posting auto-creates it. `alreadyExisted = true` is the normal, healthy result there — not a warning.');
        HelpBuilder.AppendLine('- **New locations need an Inventory Posting Setup row**: Posting the receipt fails with `The Inventory Posting Setup does not exist. ... Location Code=''{loc}'', Invt. Posting Group Code=''{grp}''` until a row exists for the location + each item''s Inventory Posting Group. Create it via `Data.Records.Set` on `Inventory Posting Setup` (copy an existing location''s accounts).');
        HelpBuilder.AppendLine('- **No-put-away locations**: If the receipt''s `Location Code` has `Require Put-away = false`, the put-away step is skipped at receipt-posting time and a manual put-away cannot be created either — you get `No Warehouse Put-away was created for ...`. The stock is already in inventory.');
        HelpBuilder.AppendLine('- **Bin-mandatory / WMS locations**: Locations with `Bin Mandatory = true` or `Directed Put-away and Pick = true` require destination bins to be configurable (default bin, put-away template, or bin policy). Without one BC raises a bin error which is returned verbatim. Put-away lines come in Take + Place pairs there.');
        HelpBuilder.AppendLine('- **Permission for `assignedUserId`**: The target user must already exist as a `Warehouse Employee` at the put-away''s `Location Code`. Otherwise BC raises `The field Assigned User ID of table Warehouse Activity Header contains a value ({user}) that cannot be found in the related table (Warehouse Employee).`');
        HelpBuilder.AppendLine('- **Sorting list drift**: The enum `Whse. Activity Sorting Method` is extensible. If `sortingMethod` is rejected, the error response contains the authoritative list for your tenant.');
        HelpBuilder.AppendLine('- **`setBreakbulkFilter` / `doNotFillQtyToHandle`**: BC report 7305 exposes these on its request page only. The wrapper rejects `true` to avoid silent loss; omit the keys (or send `false`) for default BC behaviour.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## AI-Agent Guidance');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('When orchestrating this message type from an agent:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. **Identifier resolution order is fixed**: Subject > `systemId` > `recordSystemId` > `id` > `postedWhseReceiptNo` > `receiptNo` > `no`. Pick exactly one; do not mix.');
        HelpBuilder.AppendLine('2. **Prefer SystemId over `No.`** for repeatable calls — Posted Whse. Receipt numbers come from a No. Series and may be re-issued in non-production tenants after database restores.');
        HelpBuilder.AppendLine('3. **`alreadyExisted` tells you who created the put-away**, not whether it is usable. Either way the `putawayNo` is ready for `Warehouse.Putaway.Register`. Do not treat `alreadyExisted = true` as a failure.');
        HelpBuilder.AppendLine('4. **Idempotency**: Safe to retry. A second call against the same receipt returns the same open put-away (`alreadyExisted = true`) rather than creating a duplicate — provided no put-away has been registered in between.');
        HelpBuilder.AppendLine('5. **For partial put-aways**: Modify the resulting Warehouse Activity Lines'' `Qty. to Handle` via `Data.Records.Set` before calling `Warehouse.Putaway.Register`. Remember Take + Place pairs on bin-mandatory locations.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Reproduce / Test via the BC Bifrost MCP');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('A full end-to-end test against a CRONUS-style tenant (all steps are `invoke_message_type` / `set_records` MCP tools):');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. `set_records` on `Location` — create a worksheet put-away location: `{ RequireReceive: true, RequirePutaway: true, UsePutawayWorksheet: true, BinMandatory: false }`.');
        HelpBuilder.AppendLine('2. `set_records` on `Inventory Posting Setup` — add a row for the new location + the item''s Invt. Posting Group (copy accounts from an existing location).');
        HelpBuilder.AppendLine('3. `Purchase.Document.Create` (subject = vendor No., `data: { documentType: "Order" }`) → note the PO No.');
        HelpBuilder.AppendLine('4. `set_records` on `Purchase Line` — add an item line with `LocationCode` = the new location, a `Quantity`, and a `DirectUnitCost`.');
        HelpBuilder.AppendLine('5. `Purchase.Document.Release` (subject = PO No.).');
        HelpBuilder.AppendLine('6. `Warehouse.Receipt.Create` (`data: { sourceDocuments: [{ sourceType: "PurchaseOrder", documentNo: "<PO>" }] }`). Omit `locationCode` unless it is set on the Purchase **Header** — the filter validates the header, not the line.');
        HelpBuilder.AppendLine('7. `Warehouse.Receipt.Post` (`data: { receiptNo: "<WR>" }`) → note `postedWhseReceiptNo`.');
        HelpBuilder.AppendLine('8. `Warehouse.Putaway.Create` (subject = posted receipt No.) → `alreadyExisted = false` on a worksheet location; `true` on a non-worksheet location.');
        HelpBuilder.AppendLine('9. `Warehouse.Putaway.Register` (subject = `putawayNo`).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Workflow Chain');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. `Sales.ReturnOrder.Release` (or Purchase Order release)');
        HelpBuilder.AppendLine('2. `Warehouse.Receipt.Create`');
        HelpBuilder.AppendLine('3. `Warehouse.Receipt.Post` — produces the **Posted** Whse. Receipt that this message type consumes (and, on non-worksheet locations, the put-away itself).');
        HelpBuilder.AppendLine('4. **`Warehouse.Putaway.Create`** — this message type');
        HelpBuilder.AppendLine('5. `Warehouse.Putaway.Register`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse.Receipt.Post` — produces the input (the Posted Whse. Receipt).');
        HelpBuilder.AppendLine('- `Warehouse.Putaway.Register` — registers the put-away after the warehouse worker has placed the items.');
        HelpBuilder.AppendLine('- `Data.Records.Get` — load any field on the resulting `Warehouse Activity Header` / `Warehouse Activity Line`.');

        HelpText := HelpBuilder.ToText();
    end;
}
