namespace Origo.Bifrost.Warehouse;

codeunit 10078418 "Whse Shipment Create Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Warehouse.Shipment.Create - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Creates one Warehouse Shipment per source document supplied. Wraps BC''s `Get Source Doc. Outbound` (codeunit 5752) — each Sales Order or Outbound Transfer Order produces its own Warehouse Shipment Header at the source''s location.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound (state change)  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Location Prerequisites');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('The source document''s `Location Code` must point to a Location where `Require Shipment = true`. Otherwise BC produces the source documents directly from the Sales Order / Transfer Order without going through a Warehouse Shipment.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Additional behaviour depending on the Location setup:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Location flags | Effect on Warehouse Shipment line |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `Require Shipment = true`, `Require Pick = false` | `Qty. to Ship` is populated from the source line. `Warehouse.Shipment.Post` can run immediately. |');
        HelpBuilder.AppendLine('| `Require Shipment = true`, `Require Pick = true` | `Qty. to Ship` starts at 0. Create and register a Warehouse Pick with `Warehouse.Pick.Create` then `Warehouse.Pick.Register` before `Warehouse.Shipment.Post` will accept the document. Trying to set `Qty. to Ship` manually is blocked by BC (`Qty. to Ship must not be greater than 0 units ...`). |');
        HelpBuilder.AppendLine('| `Directed Put-away and Pick = true` (e.g. WMS bin-mandatory location) | Same as Require Pick — use `Warehouse.Pick.Create` then `Warehouse.Pick.Register` before posting. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Discovery — find shipment-required locations');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Use `Data.Records.Get` on `Location` (table 14) with `tableView` `WHERE(Require Shipment=CONST(true))` to enumerate the candidates. Inspect the `RequirePick` and `DirectedPutawayandPick` fields to anticipate whether posting needs a registered pick.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Idempotency / Safety Notes');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- Not idempotent: each call inserts new Warehouse Shipment Headers from the relevant number series.');
        HelpBuilder.AppendLine('- Each source document creates a separate header (BC standard behaviour).');
        HelpBuilder.AppendLine('- Source documents that are already on an open Warehouse Shipment, have no quantity to ship, or have an active pick will fail with `No Warehouse Shipment was created`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Parameter | Type | Required | Notes |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| `sourceDocuments` | array | **Yes** | One or more `{ sourceType, documentNo }` entries. |');
        HelpBuilder.AppendLine('| `sourceDocuments[].sourceType` | string | **Yes** | `SalesOrder` or `TransferOrder` (case-insensitive). |');
        HelpBuilder.AppendLine('| `sourceDocuments[].documentNo` | code[20] | **Yes** | The source document''s `No.`. |');
        HelpBuilder.AppendLine('| `locationCode` | code[10] | No | If supplied, validates each source uses the same location. Subject to write-restriction on `Warehouse Shipment Header."Location Code"`. |');
        HelpBuilder.AppendLine('| `assignedUserId` | code[50] | No | Applied to every created header after creation. |');
        HelpBuilder.AppendLine('| `postingDate` | date | No | `YYYY-MM-DD`. Omitted: the header posting date is unchanged. An invalid value is an error. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "locationCode": "WHITE",');
        HelpBuilder.AppendLine('  "assignedUserId": "ADMIN",');
        HelpBuilder.AppendLine('  "sourceDocuments": [');
        HelpBuilder.AppendLine('    { "sourceType": "SalesOrder", "documentNo": "1001" },');
        HelpBuilder.AppendLine('    { "sourceType": "TransferOrder", "documentNo": "T-2001" }');
        HelpBuilder.AppendLine('  ]');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "noOfShipments": 2,');
        HelpBuilder.AppendLine('  "shipments": [');
        HelpBuilder.AppendLine('    {');
        HelpBuilder.AppendLine('      "recordSystemId": "00000000-0000-0000-0000-000000000000",');
        HelpBuilder.AppendLine('      "no": "WS001001",');
        HelpBuilder.AppendLine('      "locationCode": "WHITE",');
        HelpBuilder.AppendLine('      "assignedUserId": "ADMIN",');
        HelpBuilder.AppendLine('      "sourceType": "SalesOrder",');
        HelpBuilder.AppendLine('      "sourceDocumentNo": "1001",');
        HelpBuilder.AppendLine('      "linesCreated": 3');
        HelpBuilder.AppendLine('    }');
        HelpBuilder.AppendLine('  ]');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Posting Gate');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('None — creation does not post. The companion `Warehouse.Shipment.Post` requires the `BIFROST WhsePost ori` permission set.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Field Restrictions');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse Shipment Header."Location Code"` — providing `locationCode` while this field is write-restricted is denied.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `sourceDocuments is required and must contain at least one entry.` | Request missing the array or array empty. |');
        HelpBuilder.AppendLine('| `Source #{n} is missing sourceType or documentNo (both required).` | One of the entries lacks a value. |');
        HelpBuilder.AppendLine('| `Unsupported sourceType ''{value}''. Expected: SalesOrder, TransferOrder.` | Source type not recognised. |');
        HelpBuilder.AppendLine('| `Sales Header / Transfer Header "{no}" was not found (from sourceDocuments.documentNo).` (`RecordNotFound`) | The source document does not exist. |');
        HelpBuilder.AppendLine('| `... is not Released.` | Source must be Released before warehouse shipment creation. |');
        HelpBuilder.AppendLine('| `... uses location ''{x}'' which does not match the requested locationCode ''{y}''.` | When `locationCode` filter is supplied. |');
        HelpBuilder.AppendLine('| `Location ''{x}'' (from ...) does not require shipment routing` | Location card has `Require Shipment = false`. |');
        HelpBuilder.AppendLine('| `No Warehouse Shipment was created for ...` | Source already on a shipment, no qty remaining, or active pick. |');
        HelpBuilder.AppendLine('| `Field {n} is restricted for write on table {t}.` | `Bifrost Field Access` blocks `locationCode`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## End-to-End Workflow');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Concrete sequence to go from a customer to a posted shipment (values from a CRONUS-style demo).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. **Create the Sales Order** — `Sales.Document.Create`');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{ "documentType": "Order", "no": "10000" }');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('Capture `result[0].primaryKey.No_` (e.g. `"101028"`).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('2. **Add a Sales Line at the shipment-required Location** — `Data.Records.Set` on table `37` (`Sales Line`).');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "tableName": "Sales Line",');
        HelpBuilder.AppendLine('  "data": [{');
        HelpBuilder.AppendLine('    "primaryKey": { "DocumentType": "Order", "DocumentNo_": "101028", "LineNo_": 10000 },');
        HelpBuilder.AppendLine('    "fields": { "Type": "Item", "No_": "1896-S", "LocationCode": "GULUR", "Quantity": 2 }');
        HelpBuilder.AppendLine('  }]');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('3. **Release the order** — `Sales.Document.Release`');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{ "orderNo": "101028" }');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('4. **Create the Warehouse Shipment** — `Warehouse.Shipment.Create`');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{ "sourceDocuments": [ { "sourceType": "SalesOrder", "documentNo": "101028" } ] }');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('Capture `shipments[0].no` (e.g. `"SH000004"`).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('5. **If the location requires a pick** — call `Warehouse.Pick.Create` for `SH000004`, optionally adjust line-level `Qty. to Handle` via `Data.Records.Set` on `Warehouse Activity Line`, then call `Warehouse.Pick.Register`. Both message types are documented separately.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('6. **Post the shipment** — `Warehouse.Shipment.Post`');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{ "shipmentNo": "SH000004", "invoice": false }');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse.Shipment.Post` — post the created Warehouse Shipment.');
        HelpBuilder.AppendLine('- `Data.Records.Get` — load any field on the resulting `Warehouse Shipment Header` / `Warehouse Shipment Line`.');

        HelpText := HelpBuilder.ToText();
    end;
}
