namespace Origo.Bifrost.Warehouse;

codeunit 10078420 "Whse Ship. Prev. Post Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Warehouse.Shipment.PreviewPost - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Simulates posting a Warehouse Shipment and returns the ledger entries that **would** be produced — without writing anything to the database. Drives the BC `Gen. Jnl.-Post Preview.SetContext + Run()` headless flow against the `Whse.-Post Shipment (Yes/No)` subscriber, captures the in-memory entries via `Posting Preview Event Handler`, then enumerates every populated table from `FillDocumentEntry`. Typical previewed tables include `Item Ledger Entry`, `Value Entry`, `Posted Whse. Shipment Header`, `Posted Whse. Shipment Line`, `Sales Shipment Header`, `Sales Shipment Line`, plus `Sales Invoice Header`, `Sales Invoice Line`, `G/L Entry`, `VAT Entry`, `Cust. Ledger Entry` for the invoice pass. Each row is serialized through `Bifrost Preview Helper` so consumers can pick which fields they care about.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Important — Invoice flag is fixed.** BC''s `Whse.-Post Shipment (Yes/No)` preview subscriber forces `Invoice = true` for the simulated post. This message type therefore always reports the full **Ship + Invoice** impact regardless of the Warehouse Shipment header''s settings. The response `invoice` field is therefore always `true`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Returns `rollback: true` so callers know the database was untouched. Also pre-computes the LCY balance and the distinct G/L `Document No.` values that would appear on the register.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound (read-only — all changes rolled back)  **Content-Type**: `text/markdown`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Response is wrapped as a markdown document around a fenced ```json``` block so it renders inline in chat clients; the JSON inside is the structured payload below.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Shipment Identification Order');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('First match wins:');
        HelpBuilder.AppendLine('1. `subject` envelope attribute is a GUID → header SystemId.');
        HelpBuilder.AppendLine('2. `subject` envelope attribute non-empty text → header `No.`.');
        HelpBuilder.AppendLine('3. `data.systemId` / `data.recordSystemId` / `data.id` → header SystemId.');
        HelpBuilder.AppendLine('4. `data.shipmentNo` / `data.no` → header `No.`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Parameter | Type | Required | Notes |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| `shipmentNo` | string | See above | Warehouse Shipment `No.` (Code[20]). |');
        HelpBuilder.AppendLine('| `no` | string | See above | Alias for `shipmentNo`. |');
        HelpBuilder.AppendLine('| `systemId` / `recordSystemId` / `id` | string (GUID) | See above | Warehouse Shipment Header SystemId. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{ "shipmentNo": "WS00001" }');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "entryCount": 10,');
        HelpBuilder.AppendLine('  "glEntryCount": 4,');
        HelpBuilder.AppendLine('  "rollback": true,');
        HelpBuilder.AppendLine('  "summary": "Preview-posting warehouse shipment WS00001 (2 lines, Ship + Invoice) would create 10 ledger entries across 6 tables. Transaction is balanced.",');
        HelpBuilder.AppendLine('  "shipmentNo": "WS00001",');
        HelpBuilder.AppendLine('  "locationCode": "WHITE",');
        HelpBuilder.AppendLine('  "invoice": true,');
        HelpBuilder.AppendLine('  "linesToPost": 2,');
        HelpBuilder.AppendLine('  "postingDate": "2026-04-15",');
        HelpBuilder.AppendLine('  "lcyCode": "USD",');
        HelpBuilder.AppendLine('  "predictedNumbers": ["INV00012"],');
        HelpBuilder.AppendLine('  "totals": { "balanced": true, "totalDebitLCY": 250.0, "totalCreditLCY": 250.0 },');
        HelpBuilder.AppendLine('  "preview": [');
        HelpBuilder.AppendLine('    {');
        HelpBuilder.AppendLine('      "tableId": 32,');
        HelpBuilder.AppendLine('      "tableName": "Item Ledger Entry",');
        HelpBuilder.AppendLine('      "tableCaption": "Item Ledger Entry",');
        HelpBuilder.AppendLine('      "entryCount": 1,');
        HelpBuilder.AppendLine('      "entries": [');
        HelpBuilder.AppendLine('        {');
        HelpBuilder.AppendLine('          "id": "00000000-0000-0000-0000-000000000000",');
        HelpBuilder.AppendLine('          "primaryKey": { "EntryNo_": "1" },');
        HelpBuilder.AppendLine('          "fields": { "ItemNo_": "1000", "DocumentNo_": "***", "Quantity": "-5", "LocationCode": "WHITE" }');
        HelpBuilder.AppendLine('        }');
        HelpBuilder.AppendLine('      ]');
        HelpBuilder.AppendLine('    },');
        HelpBuilder.AppendLine('    {');
        HelpBuilder.AppendLine('      "tableId": 17,');
        HelpBuilder.AppendLine('      "tableName": "G/L Entry",');
        HelpBuilder.AppendLine('      "tableCaption": "G/L Entry",');
        HelpBuilder.AppendLine('      "entryCount": 4,');
        HelpBuilder.AppendLine('      "entries": []');
        HelpBuilder.AppendLine('    }');
        HelpBuilder.AppendLine('  ]');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Response Fields');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Field | Type | Notes |');
        HelpBuilder.AppendLine('|---|---|---|');
        HelpBuilder.AppendLine('| `rollback` | bool | Always `true` for this message type. |');
        HelpBuilder.AppendLine('| `entryCount` | int | On every Success answer: the number of captured entries. |');
        HelpBuilder.AppendLine('| `glEntryCount` | int | On every Success answer: the number of captured G/L entries. |');
        HelpBuilder.AppendLine('| `summary` | string | One-line human-readable recap. |');
        HelpBuilder.AppendLine('| `shipmentNo` / `locationCode` | string | Identifying header fields. |');
        HelpBuilder.AppendLine('| `invoice` | bool | Always `true` — BC''s preview subscriber forces Ship + Invoice. |');
        HelpBuilder.AppendLine('| `linesToPost` | int | Warehouse Shipment Lines fed into the preview. |');
        HelpBuilder.AppendLine('| `postingDate` | string | `Posting Date` of the shipment header. |');
        HelpBuilder.AppendLine('| `lcyCode` | string | `GLSetup."LCY Code"`. |');
        HelpBuilder.AppendLine('| `predictedNumbers` | string[] | Distinct `Document No.` values across the previewed G/L entries (typically the future Sales Invoice No., Posted Whse. Shipment No., etc.). May contain the literal `"***"` when BC''s preview engine masks an unassigned number-series value. |');
        HelpBuilder.AppendLine('| `totals.balanced` | bool | Present only when G/L entries were captured (`glEntryCount > 0`): `true` when `Round(totalDebitLCY - totalCreditLCY, 0.01) = 0`. Omitted when the posting creates no G/L entry. |');
        HelpBuilder.AppendLine('| `totals.totalDebitLCY` / `totalCreditLCY` | decimal | Aggregated from the previewed G/L entries. |');
        HelpBuilder.AppendLine('| `preview[]` | array | One element per populated ledger / posted-document table that BC would write to. |');
        HelpBuilder.AppendLine('| `preview[].tableId` / `tableName` | int / string | BC table identification. |');
        HelpBuilder.AppendLine('| `preview[].tableCaption` | string | BC `RecordRef.Caption` for the table (display name). |');
        HelpBuilder.AppendLine('| `preview[].entryCount` | int | Number of entries that would be inserted into this table. |');
        HelpBuilder.AppendLine('| `preview[].entries[]` | array | Per-entry objects with `id` (placeholder SystemId GUID), `primaryKey` (object of PK field-name → value), and `fields` (all serialized fields). Field names follow the same normalization as `Data.Records.Get` (`.`/`/`/`%`/`"`/`\`/`''` → `_`, strip remaining non-alphanumerics). `DocumentNo_` values inside `fields` are commonly `"***"` when BC masks an unassigned number-series. Subscribe to `OnGetPreviewFieldNames` to control which fields appear; subscribe to `OnPrecalculateFlowFields` to pre-compute FlowFields before serialization. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Examples (from unit tests)');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('From `Whse Ship. Prev. Post Tests` (codeunit 95439):');
        HelpBuilder.AppendLine('- `PreviewPost_PostableShipment_ReturnsSuccessAndRollback` — verifies `status: "Success"`, `rollback: true`, and that the shipment lines remain after the preview (no commit).');
        HelpBuilder.AppendLine('- `PreviewPost_PostableShipment_DoesNotPostShipment` — verifies no `Posted Whse. Shipment Header` row is actually persisted.');
        HelpBuilder.AppendLine('- `PreviewPost_PostableShipment_ReturnsContextAndPreviewArray` — verifies the shipment context fields and that `preview[]` contains at least one populated table.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Preview Outcome');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('The preview answers `Success` only when it captured at least one entry. Every Success answer carries `entryCount` (all captured entries) and `glEntryCount` (the G/L entries among them).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- **Nothing would be posted** (no entry captured, or BC reports that there is nothing to post): `status: Error`, `code: NothingToPreview`, `error: "The preview produced no entries. Nothing would be posted."` and a `nextStep`: No shipment line has Qty. to Ship. Set quantities on the shipment lines.');
        HelpBuilder.AppendLine('- **No G/L entries** (for example item or value entries with Automatic Cost Posting off): `Success` with `glEntryCount: 0` and **no** `totals.balanced`; the summary says "No G/L entries would be posted."');
        HelpBuilder.AppendLine('- **G/L entries**: `totals.balanced` as described above.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('A Business Central posting error raised during the preview is returned verbatim, with no `code`. The catch-all below is used only when the preview run fails and Business Central returns no error text. A preview that runs and captures no entries is `NothingToPreview`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `The preview produced no entries. Nothing would be posted.` (`NothingToPreview`) | Nothing would be posted, including when every line has `Qty. to Ship = 0`. On a WMS location (`Require Pick = true`) that is what you see before a warehouse pick is registered — registration writes `Qty. to Ship`. See Operational Notes. `nextStep`: No shipment line has Qty. to Ship. Set quantities on the shipment lines. |');
        HelpBuilder.AppendLine('| `Warehouse Shipment Header identifier is missing. Pass it as the subject, or as one of: systemId, recordSystemId, id, shipmentNo, no.` (`MissingParameter`) | No identifier in `subject` or the request JSON. |');
        HelpBuilder.AppendLine('| `Warehouse Shipment Header "{value}" was not found (from {subject or key}).` (`RecordNotFound`) | An identifier was given but matches no record; `parameter` and `received` name it. Every identifier supplied is tried. |');
        HelpBuilder.AppendLine('| `The identifiers in {a} and {b} point to different records.` (`ConflictingIdentifiers`) | Two identifiers were given that resolve to different records. |');
        HelpBuilder.AppendLine('| `"{value}" is not a valid GUID` / `integer` `(from {key}).` (`InvalidParameterFormat`) | A SystemId or entry number that cannot be read. |');
        HelpBuilder.AppendLine('| `Warehouse Shipment {no} has no lines to post.` (`NothingToPreview`) | The header has no lines. `nextStep`: No shipment line has Qty. to Ship. Set quantities on the shipment lines. |');
        HelpBuilder.AppendLine('| `Posting preview failed and no entries were captured. The shipment cannot be posted in its current state.` | The preview run failed and Business Central returned no error text. Returned with no `code`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Operational Notes');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- **WMS locations require a registered pick first.** On a location with `Require Pick = true` (e.g. CRONUS `WHITE` / `GULUR`), the Warehouse Shipment lines start with `Qty. to Ship = 0`. The warehouse pick must be created **and registered** before previewing — pick registration is what writes `Qty. to Ship` back onto the shipment lines.');
        HelpBuilder.AppendLine('- **Locations with `Require Shipment = true` and `Require Pick = false`** behave like a basic shipping flow: `Qty. to Ship` is populated when the shipment line is created, so the preview runs directly without a pick step.');
        HelpBuilder.AppendLine('- **Invoice flag is fixed at `true`.** The Ship + Invoice impact is always reported regardless of how you would post in production. To preview Ship-only behaviour, use the source document''s own posting preview (e.g. `Sales.Order.PreviewPost` once available, or post the shipment with `Warehouse.Shipment.Post` after registering picks).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse.Shipment.Create` — create a Warehouse Shipment from a source document.');
        HelpBuilder.AppendLine('- `Warehouse.Shipment.Post` — commit the actual post (with or without invoice).');
        HelpBuilder.AppendLine('- `Finance.GeneralJournal.PreviewPost` — same pattern for the general journal.');

        HelpText := HelpBuilder.ToText();
    end;
}
