namespace Origo.Bifrost.Warehouse;

codeunit 10078424 "Whse Pick Create Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Warehouse.Pick.Create - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Creates a Warehouse Pick from an existing Warehouse Shipment. Wraps BC report 7318 `Whse.-Shipment - Create Pick` (the same action invoked by *Create Pick* on the Warehouse Shipment page). The resulting `Warehouse Activity Header` (`Type = Pick`) is returned along with line totals.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound (state change)  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Prerequisites');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- The Warehouse Shipment must exist and have at least one line.');
        HelpBuilder.AppendLine('- The shipment''s `Location Code` must point to a Location with `Require Pick = true` (typically a Directed Put-away and Pick / WMS location). On Locations with `Require Shipment = true, Require Pick = false`, no pick is needed — call `Warehouse.Shipment.Post` directly.');
        HelpBuilder.AppendLine('- Sufficient inventory must exist in the source bins so BC has something to pick.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Identifying the Warehouse Shipment');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Provide the shipment via the Bifrost Subject (GUID = SystemId, or text = `No.`) or via one of these request JSON keys:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Key | Meaning |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `systemId` / `recordSystemId` / `id` | SystemId of the `Warehouse Shipment Header`. |');
        HelpBuilder.AppendLine('| `whseShipmentNo` / `shipmentNo` / `no` | `No.` of the `Warehouse Shipment Header`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Parameter | Type | Required | Notes |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| `whseShipmentNo` | code[20] | One identifier required | Or use `shipmentNo` / `no` / `systemId` / Subject. |');
        HelpBuilder.AppendLine('| `assignedUserId` | code[50] | No | Applied to the created Warehouse Pick. Subject to write-restriction on `Warehouse Activity Header."Assigned User ID"`. |');
        HelpBuilder.AppendLine('| `sortingMethod` | string | No | Case-insensitive name from BC enum `Whse. Activity Sorting Method` — currently: `None`, `Item`, `Document`, `Shelf or Bin`, `Due Date`, `Ship-To`, `Bin Ranking`, `Action Type` (BC 27). The error response lists the exact set valid on your build. Subject to write-restriction on `Warehouse Activity Header."Sorting Method"`. |');
        HelpBuilder.AppendLine('| `setBreakbulkFilter` | boolean | No (default false) | Not supported in this API version. Sending `true` returns an error. |');
        HelpBuilder.AppendLine('| `doNotFillQtyToHandle` | boolean | No (default false) | Not supported in this API version. Sending `true` returns an error. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "whseShipmentNo": "WS001001",');
        HelpBuilder.AppendLine('  "assignedUserId": "ADMIN",');
        HelpBuilder.AppendLine('  "sortingMethod": "Bin Ranking"');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "whseShipmentNo": "WS001001",');
        HelpBuilder.AppendLine('  "pickNo": "WPK000123",');
        HelpBuilder.AppendLine('  "pickSystemId": "00000000-0000-0000-0000-000000000000",');
        HelpBuilder.AppendLine('  "locationCode": "WHITE",');
        HelpBuilder.AppendLine('  "assignedUserId": "ADMIN",');
        HelpBuilder.AppendLine('  "sortingMethod": "Bin Ranking",');
        HelpBuilder.AppendLine('  "totalPickLines": 4,');
        HelpBuilder.AppendLine('  "totalQtyToHandle": 12,');
        HelpBuilder.AppendLine('  "message": "Warehouse Pick WPK000123 created from Shipment WS001001 with 4 lines."');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('When no `sortingMethod` is supplied, the response returns `"sortingMethod": "None"` (the BC enum''s blank/whitespace caption is normalised to `None`).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Posting Gate');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('None — pick creation does not register stock movement. The companion `Warehouse.Pick.Register` requires the `BIFROST WhsePost ori` permission set.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Field Restrictions');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Before applying caller-supplied values to the created Warehouse Pick, the implementation calls `Bifrost Field Access.IsFieldWriteRestricted` on:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse Activity Header."Assigned User ID"` (when `assignedUserId` is supplied)');
        HelpBuilder.AppendLine('- `Warehouse Activity Header."Sorting Method"` (when `sortingMethod` is supplied)');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('A restricted field aborts the request with an Error response — the pick still exists on disk; remove or rerun without the restricted parameter.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `Warehouse Shipment Header identifier is missing. Pass it as the subject, or as one of: systemId, recordSystemId, id, whseShipmentNo, shipmentNo, no.` (`MissingParameter`) | No identifier in `subject` or the request JSON. |');
        HelpBuilder.AppendLine('| `Warehouse Shipment Header "{value}" was not found (from {subject or key}).` (`RecordNotFound`) | An identifier was given but matches no record; `parameter` and `received` name it. Every identifier supplied is tried. |');
        HelpBuilder.AppendLine('| `The identifiers in {a} and {b} point to different records.` (`ConflictingIdentifiers`) | Two identifiers were given that resolve to different records. |');
        HelpBuilder.AppendLine('| `"{value}" is not a valid GUID` / `integer` `(from {key}).` (`InvalidParameterFormat`) | A SystemId or entry number that cannot be read. |');
        HelpBuilder.AppendLine('| `Warehouse Shipment {n} has no lines to pick.` | Shipment header exists but has zero lines. |');
        HelpBuilder.AppendLine('| `sortingMethod ''{x}'' is not valid. Expected one of: ...` | Value not in `Whse. Activity Sorting Method.Names()`. |');
        HelpBuilder.AppendLine('| `Field {n} is restricted for write on table {t}.` | `Bifrost Field Access` blocks `assignedUserId` or `sortingMethod`. |');
        HelpBuilder.AppendLine('| `... = true is not supported by this API version.` | `setBreakbulkFilter` or `doNotFillQtyToHandle` supplied as `true`. |');
        HelpBuilder.AppendLine('| `No Warehouse Pick was created for ...` | BC report ran without errors but produced no activity header (nothing to pick, pick already exists, location does not require a pick). |');
        HelpBuilder.AppendLine('| `Nothing to handle.` / `There is nothing to create.` | BC report error surfaced as Bifrost Error — no available inventory in source bins. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Pitfalls');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- **Pick already exists**: BC report 7318 silently produces nothing if an open Warehouse Pick for the Shipment is already on disk. The wrapper surfaces this as `No Warehouse Pick was created for ...`. Inspect `Warehouse Activity Header` (`Type = Pick`, `Whse. Document No.` = your shipment) before deciding to retry.');
        HelpBuilder.AppendLine('- **No-pick locations**: If the Shipment''s `Location Code` has `Require Pick = false`, BC will not create a pick — you get the same `No Warehouse Pick was created for ...` error. Call `Warehouse.Shipment.Post` directly.');
        HelpBuilder.AppendLine('- **Insufficient inventory**: BC report 7318 only creates lines for what is currently available in the source bins, including reservations against other documents. A shipment with `Quantity = 5` may produce a pick with `totalQtyToHandle < 5`. Always compare `totalQtyToHandle` against the shipment line totals before treating the call as fully successful.');
        HelpBuilder.AppendLine('- **Bin-mandatory / WMS locations**: Locations with `Bin Mandatory = true` or `Directed Put-away and Pick = true` require source bins to be configured and items to be put away. Without put-away, the pick is empty and you get `No Warehouse Pick was created for ...`.');
        HelpBuilder.AppendLine('- **Permission for `assignedUserId`**: The target user must already exist as a `Warehouse Employee` at the pick''s `Location Code`. Otherwise BC raises `The field Assigned User ID of table Warehouse Activity Header contains a value ({user}) that cannot be found in the related table (Warehouse Employee).`');
        HelpBuilder.AppendLine('- **Sorting list drift**: The enum `Whse. Activity Sorting Method` is extensible — Microsoft has historically added values. The list above reflects BC 27. If `sortingMethod` is rejected, the error response contains the authoritative list for your tenant.');
        HelpBuilder.AppendLine('- **`setBreakbulkFilter` / `doNotFillQtyToHandle`**: BC report 7318 exposes these on its request page only. The wrapper rejects `true` to avoid silent loss; omit the keys (or send `false`) for default BC behaviour.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## AI-Agent Guidance');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('When orchestrating this message type from an agent:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. **Identifier resolution order is fixed**: Subject > `systemId` > `recordSystemId` > `id` > `whseShipmentNo` > `shipmentNo` > `no`. Pick exactly one; do not mix.');
        HelpBuilder.AppendLine('2. **Prefer SystemId over `No.`** for repeatable calls — the No. series changes when a Warehouse Shipment is posted/deleted.');
        HelpBuilder.AppendLine('3. **Treat `status: "Success"` plus `totalPickLines == 0` as a soft failure** — it means the pick exists but cannot move stock; do not chain to `Warehouse.Pick.Register`.');
        HelpBuilder.AppendLine('4. **Idempotency**: This message type is **not** idempotent. If a transient error occurs after BC report 7318 ran but before the response was returned, a retry may create a second pick. Always look up existing picks for the Shipment before retrying.');
        HelpBuilder.AppendLine('5. **For partial picks**: Pre-update `Quantity` / `Qty. Outstanding` on the Warehouse Shipment Lines before calling Pick.Create, or modify the resulting Warehouse Activity Lines'' `Qty. to Handle` via `Data.Records.Set` before calling `Warehouse.Pick.Register`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Workflow Chain');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. `Sales.Document.Release` (or Transfer Order release)');
        HelpBuilder.AppendLine('2. `Warehouse.Shipment.Create`');
        HelpBuilder.AppendLine('3. **`Warehouse.Pick.Create`** — this message type');
        HelpBuilder.AppendLine('4. `Warehouse.Pick.Register`');
        HelpBuilder.AppendLine('5. `Warehouse.Shipment.Post`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse.Shipment.Create` — produces the input.');
        HelpBuilder.AppendLine('- `Warehouse.Pick.Register` — registers the pick after the warehouse worker has picked the items.');
        HelpBuilder.AppendLine('- `Warehouse.Shipment.Post` — final step after the pick is registered.');
        HelpBuilder.AppendLine('- `Data.Records.Get` — load any field on the resulting `Warehouse Activity Header` / `Warehouse Activity Line`.');

        HelpText := HelpBuilder.ToText();
    end;
}
