namespace Origo.Bifrost.Warehouse;

codeunit 10078425 "Whse Pick Register Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Warehouse.Pick.Register - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Registers a Warehouse Pick. Wraps BC codeunit 7307 `Whse.-Activity-Register`. After registration the source `Warehouse Shipment Line` rows receive the picked quantity (`Qty. Picked` and `Qty. to Ship`), the pick header moves to history (`Registered Whse. Activity Hdr.`), and the originating Warehouse Shipment becomes eligible for `Warehouse.Shipment.Post`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound (state change)  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Posting Gate');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Requires the `BIFROST WhsePost ori` permission set on the message-task user. Without it the request returns an Error response and nothing is registered.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Identifying the Warehouse Pick');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Provide the pick via the Bifrost Subject (GUID = SystemId of the activity header, or text = `No.`) or via one of these request JSON keys:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Key | Meaning |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `systemId` / `recordSystemId` / `id` | SystemId of the `Warehouse Activity Header` (Type = Pick). |');
        HelpBuilder.AppendLine('| `pickNo` / `no` | `No.` of the `Warehouse Activity Header` (Type = Pick). |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Pre-condition: Lines Must Have Qty. to Handle');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('BC registers only what the warehouse worker has confirmed picked. By default `Warehouse.Pick.Create` populates `Qty. to Handle` on every line (the `doNotFillQtyToHandle = false` default of the BC report). If you call `Warehouse.Pick.Register` against a pick with zero `Qty. to Handle` on every line, BC raises `Nothing to register.`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('To register a partial pick, first call `Data.Records.Set` on `Warehouse Activity Line` to update `Qty. to Handle` per line.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Parameter | Type | Required | Notes |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| `pickNo` | code[20] | One identifier required | Or use `no` / `systemId` / Subject. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{ "pickNo": "WPK000123" }');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "pickNo": "WPK000123",');
        HelpBuilder.AppendLine('  "linesRegistered": 4,');
        HelpBuilder.AppendLine('  "totalQtyRegistered": 12,');
        HelpBuilder.AppendLine('  "shipmentNo": "WS001001",');
        HelpBuilder.AppendLine('  "shipmentSystemId": "00000000-0000-0000-0000-000000000000",');
        HelpBuilder.AppendLine('  "registeredPickNo": "RWPK000123",');
        HelpBuilder.AppendLine('  "registeredPickSystemId": "00000000-0000-0000-0000-000000000000",');
        HelpBuilder.AppendLine('  "shipmentLines": [');
        HelpBuilder.AppendLine('    {');
        HelpBuilder.AppendLine('      "shipmentNo": "WS001001",');
        HelpBuilder.AppendLine('      "lineNo": 10000,');
        HelpBuilder.AppendLine('      "sourceDocument": "Sales Order",');
        HelpBuilder.AppendLine('      "sourceNo": "101028",');
        HelpBuilder.AppendLine('      "sourceLineNo": 10000,');
        HelpBuilder.AppendLine('      "itemNo": "1896-S",');
        HelpBuilder.AppendLine('      "qty": 2,');
        HelpBuilder.AppendLine('      "qtyPicked": 2,');
        HelpBuilder.AppendLine('      "qtyToShip": 2,');
        HelpBuilder.AppendLine('      "qtyOutstanding": 2');
        HelpBuilder.AppendLine('    }');
        HelpBuilder.AppendLine('  ],');
        HelpBuilder.AppendLine('  "message": "Warehouse Pick WPK000123 (4 lines) registered against Warehouse Shipment WS001001."');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('`qtyOutstanding` mirrors the BC `Warehouse Shipment Line."Qty. Outstanding"` flow — it is `Quantity - Qty. Shipped`. Pick registration does **not** ship, so `qtyOutstanding` stays at the line `Quantity` until `Warehouse.Shipment.Post` runs.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Field Restrictions');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('None — this message type does not accept any caller-supplied field overrides.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `Warehouse Activity Header identifier is missing. Pass it as the subject, or as one of: systemId, recordSystemId, id, pickNo, no.` (`MissingParameter`) | No identifier in `subject` or the request JSON. |');
        HelpBuilder.AppendLine('| `Warehouse Activity Header "{value}" was not found (from {subject or key}).` (`RecordNotFound`) | An identifier was given but matches no record; `parameter` and `received` name it. Every identifier supplied is tried. |');
        HelpBuilder.AppendLine('| `The identifiers in {a} and {b} point to different records.` (`ConflictingIdentifiers`) | Two identifiers were given that resolve to different records. |');
        HelpBuilder.AppendLine('| `Warehouse Activity {n} is not of Type Pick.` | Activity exists but is a Put-away / Movement / Invt. Pick. |');
        HelpBuilder.AppendLine('| `Warehouse Pick {n} has no lines.` | Header exists with zero lines (shouldn''t happen for picks created by BC). |');
        HelpBuilder.AppendLine('| `Nothing to register.` | All lines have `Qty. to Handle = 0`. |');
        HelpBuilder.AppendLine('| `Posting denied: missing ''BIFROST WhsePost ori'' permission set.` | Caller lacks the warehouse posting permission. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Pitfalls');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- **Pick header disappears after registration**: On `Success` the `Warehouse Activity Header` row is deleted and a `Registered Whse. Activity Hdr.` row appears. A second `Warehouse.Pick.Register` call against the same `pickNo` therefore returns `RecordNotFound` (`Warehouse Activity Header "{n}" was not found (from pickNo).`) — that is the success indicator, not a failure. Read the history via `Data.Records.Get` on `Registered Whse. Activity Hdr.` (filter by `Whse. Activity No.`).');
        HelpBuilder.AppendLine('- **Activity Type filter**: `Warehouse Activity Header` is shared by Picks, Put-aways, Movements, and Invt. Picks. The wrapper checks `Type = Pick` and rejects others — but make sure the `pickNo` / SystemId you supply is genuinely a Pick.');
        HelpBuilder.AppendLine('- **Partial picks need `Data.Records.Set` first**: BC fills `Qty. to Handle` automatically when the pick is created. If the warehouse worker picked less, update each line''s `Qty. to Handle` via `Data.Records.Set` on `Warehouse Activity Line` (primaryKey = `Activity Type`, `No.`, `Line No.`) before calling Register. Zero `Qty. to Handle` across all lines yields `Nothing to register.`');
        HelpBuilder.AppendLine('- **Both Take and Place lines**: BC pick lines come in pairs — one `Action Type = Take` and one `Action Type = Place` per source line. When updating `Qty. to Handle`, update **both** rows to the same value or BC rejects the register with `Qty. to Handle (Base) in the line must be equal to ...`.');
        HelpBuilder.AppendLine('- **Source Shipment must still be Released**: If the source `Warehouse Shipment` was deleted/reopened after pick creation, registration fails. The wrapper surfaces the BC error text verbatim via `GetLastErrorText`.');
        HelpBuilder.AppendLine('- **Posting gate**: The message-task user must have `BIFROST WhsePost ori` even though no inventory ledger entries are produced by registration — BC still treats it as a warehouse posting action.');
        HelpBuilder.AppendLine('- **Does not ship**: Registration only updates `Qty. Picked` and `Qty. to Ship` on the Warehouse Shipment Line — `Qty. Outstanding` is unchanged until `Warehouse.Shipment.Post` runs.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## AI-Agent Guidance');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('When orchestrating this message type from an agent:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. **Every identifier sent is tried**: `subject`, `systemId`, `recordSystemId`, `id`, `pickNo` and `no`. Two that point to different activities give `ConflictingIdentifiers`; send one.');
        HelpBuilder.AppendLine('2. **Capture `registeredPickSystemId` from the response** if you need to navigate to the history record afterwards — re-deriving it from `pickNo` after registration requires a `Registered Whse. Activity Hdr.` lookup keyed on `Whse. Activity No.`.');
        HelpBuilder.AppendLine('3. **Treat `RecordNotFound` on a known pick as evidence the pick was already registered** (the activity header moved to history). Confirm by reading `Registered Whse. Activity Hdr.` before retrying.');
        HelpBuilder.AppendLine('4. **Idempotency**: This message type is **not** idempotent — second successful invocation against the same `pickNo` is impossible because the header is gone. Use `Registered Whse. Activity Hdr.` to check whether registration already happened.');
        HelpBuilder.AppendLine('5. **Workflow continuation**: On `Success`, the originating Warehouse Shipment is ready for `Warehouse.Shipment.Post`. The response includes `shipmentNo` and `shipmentSystemId` for that chained call.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Workflow Chain');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. `Sales.Document.Release` (or Transfer Order release)');
        HelpBuilder.AppendLine('2. `Warehouse.Shipment.Create`');
        HelpBuilder.AppendLine('3. `Warehouse.Pick.Create`');
        HelpBuilder.AppendLine('4. **`Warehouse.Pick.Register`** — this message type');
        HelpBuilder.AppendLine('5. `Warehouse.Shipment.Post`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse.Pick.Create` — produces the input.');
        HelpBuilder.AppendLine('- `Warehouse.Shipment.Post` — call after registration to ship the Warehouse Shipment.');
        HelpBuilder.AppendLine('- `Data.Records.Set` on `Warehouse Activity Line` — to adjust `Qty. to Handle` before registering a partial pick.');
        HelpBuilder.AppendLine('- `Data.Records.Get` — load any field on the resulting `Registered Whse. Activity Hdr.` / `Registered Whse. Activity Line`.');

        HelpText := HelpBuilder.ToText();
    end;
}
