namespace Origo.Bifrost.Warehouse;

codeunit 10078423 "Whse Rcpt Post Prev. Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Warehouse.Receipt.Post.Preview - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Simulates posting a Warehouse Receipt and returns the captured ledger entries (Item Ledger and Value Entry — see Captured Tables below) without committing. The post is driven through `Whse.-Post Receipt (Yes/No)` (codeunit 5761) bound with `EventSubscriberInstance = Manual`, whose `OnRunPreview` subscriber sets preview mode on `Whse.-Post Receipt` (5760). The transaction is rolled back after capture via BC''s Posting Preview Event Handler.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Use this to verify what `Warehouse.Receipt.Post` would produce — predicted posted document numbers and ledger impact — before committing.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound (no state change — rolled back)  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Captured Tables');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('BC''s Posting Preview only captures inserts into a fixed whitelist of tables. For a Warehouse Receipt post the captured set is:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Table ID | Table | Always present? |');
        HelpBuilder.AppendLine('|---|---|---|');
        HelpBuilder.AppendLine('| 32 | Item Ledger Entry | Yes — one entry per receipt line. |');
        HelpBuilder.AppendLine('| 5802 | Value Entry | Yes — one Direct Cost entry per receipt line. |');
        HelpBuilder.AppendLine('| 17 | G/L Entry | Only if cost adjustment runs inline. Receipts normally produce **none**. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('`Posted Whse. Receipt Header` (table 7320) is **NOT** in BC''s preview whitelist — so the impl never observes its insert during preview. As a result `predictedNumbers.postedWhseReceiptNo` is always emitted but is **always empty** in the response. (Confirmed via live MCP test.)');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Preconditions');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Same as `Warehouse.Receipt.Post`: the Warehouse Receipt Header must exist, contain at least one line with `Qty. to Receive > 0`, and any directed put-away bin requirements must already be satisfied.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Identifier Resolution Order');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. `subject` field (GUID → `SystemId`, text → `No.`).');
        HelpBuilder.AppendLine('2. Request JSON `systemId` / `recordSystemId` / `id` (GUID).');
        HelpBuilder.AppendLine('3. Request JSON `receiptNo` / `no` (text).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Idempotency / Safety Notes');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- **Read-only**: BC''s Gen. Jnl.-Post Preview always rolls back the transaction after capturing entries. No data is persisted.');
        HelpBuilder.AppendLine('- No Posting Gate required (no state change).');
        HelpBuilder.AppendLine('- Number series advance and then roll back — the predicted posted document numbers are the numbers BC would have assigned but are released back to the series.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Parameter | Type | Required | Notes |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| `subject` | text/guid | One identifier required | Bifrost subject. |');
        HelpBuilder.AppendLine('| `systemId` / `recordSystemId` / `id` | guid | (alternative) | In request JSON. |');
        HelpBuilder.AppendLine('| `receiptNo` / `no` | code[20] | (alternative) | In request JSON. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{ "receiptNo": "WR001001" }');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Verified live (Purchase Order receipt at GULUR, 5 × item 1896-S):');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "entryCount": 2,');
        HelpBuilder.AppendLine('  "glEntryCount": 0,');
        HelpBuilder.AppendLine('  "rollback": true,');
        HelpBuilder.AppendLine('  "summary": "Warehouse Receipt RE000010 at GULUR preview produced 2 entries. No G/L entries would be posted.",');
        HelpBuilder.AppendLine('  "receiptNo": "RE000010",');
        HelpBuilder.AppendLine('  "locationCode": "GULUR",');
        HelpBuilder.AppendLine('  "sourceDocuments": [');
        HelpBuilder.AppendLine('    { "sourceDocument": "Purchase Order", "sourceNo": "106031" }');
        HelpBuilder.AppendLine('  ],');
        HelpBuilder.AppendLine('  "lcyCode": "ISK",');
        HelpBuilder.AppendLine('  "predictedNumbers": {');
        HelpBuilder.AppendLine('    "postedWhseReceiptNo": "",');
        HelpBuilder.AppendLine('    "postedPurchaseReceiptNo": "***"');
        HelpBuilder.AppendLine('  },');
        HelpBuilder.AppendLine('  "totals": {');
        HelpBuilder.AppendLine('    "totalDebitLCY": 0.0,');
        HelpBuilder.AppendLine('    "totalCreditLCY": 0.0');
        HelpBuilder.AppendLine('  },');
        HelpBuilder.AppendLine('  "preview": [');
        HelpBuilder.AppendLine('    { "tableId": 32, "tableName": "Item Ledger Entry", "entryCount": 1, "entries": ["...rows with DocumentNo_ redacted to ***..."] },');
        HelpBuilder.AppendLine('    { "tableId": 5802, "tableName": "Value Entry", "entryCount": 1, "entries": ["...rows with DocumentNo_ redacted to ***..."] }');
        HelpBuilder.AppendLine('  ]');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Response Fields');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Field | Type | Notes |');
        HelpBuilder.AppendLine('|---|---|---|');
        HelpBuilder.AppendLine('| `entryCount` | int | On every Success answer: the number of captured entries. |');
        HelpBuilder.AppendLine('| `glEntryCount` | int | On every Success answer: the number of captured G/L entries. `0` on a receipt that creates no G/L entry. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Number Redaction (`***`)');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('BC''s Posting Preview redacts assigned document numbers to `***` to signal they were rolled back rather than persisted. Affects:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `predictedNumbers.postedPurchaseReceiptNo` / `postedReturnReceiptNo` / `postedTransferReceiptNo` — always `***` for Posting Preview.');
        HelpBuilder.AppendLine('- `preview[].entries[].fields.DocumentNo_` on Item Ledger Entry / Value Entry rows — also `***`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Treat `***` as "the system would have assigned a number from the corresponding No. Series". Use `Warehouse.Receipt.Post` to obtain the actual number.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Predicted Numbers — which key appears');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Source on the receipt | Key in `predictedNumbers` | Value in preview |');
        HelpBuilder.AppendLine('|---|---|---|');
        HelpBuilder.AppendLine('| Purchase Order | `postedPurchaseReceiptNo` | `***` (redacted by BC) |');
        HelpBuilder.AppendLine('| Sales Return Order | `postedReturnReceiptNo` | `***` (redacted by BC) |');
        HelpBuilder.AppendLine('| Inbound Transfer Order | `postedTransferReceiptNo` | `***` (redacted by BC) |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('`postedWhseReceiptNo` is always emitted but is **always empty** in preview because BC''s Posting Preview does not capture inserts into `Posted Whse. Receipt Header` (table 7320). To obtain the real number, run `Warehouse.Receipt.Post`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Totals — balanced flag');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Warehouse receipts often have **no direct G/L impact** (inventory recognised at cost, not at booking): then `glEntryCount` is 0, `totals.balanced` is omitted and `totalDebitLCY = totalCreditLCY = 0`. If the receipt triggers an automatic cost adjustment, the captured G/L entries appear in `preview`, and `totals.balanced` says whether they balance.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Posting Gate');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('None — preview does not commit.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Field Restrictions');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('None.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Preview Outcome');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('The preview answers `Success` only when it captured at least one entry. Every Success answer carries `entryCount` (all captured entries) and `glEntryCount` (the G/L entries among them).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- **Nothing would be posted** (no entry captured, or BC reports that there is nothing to post): `status: Error`, `code: NothingToPreview`, `error: "The preview produced no entries. Nothing would be posted."` and a `nextStep`: No receipt line has Qty. to Receive. Set quantities on the receipt lines.');
        HelpBuilder.AppendLine('- **No G/L entries** (for example item or value entries with Automatic Cost Posting off): `Success` with `glEntryCount: 0` and **no** `totals.balanced`; the summary says "No G/L entries would be posted."');
        HelpBuilder.AppendLine('- **G/L entries**: `totals.balanced` as described above.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('A Business Central posting error raised during the preview is returned verbatim, with no `code` (for example a missing Bin Code or a blocked item). The catch-all below is used only when the preview run fails and Business Central returns no error text. A preview that runs and captures no entries is `NothingToPreview`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `The preview produced no entries. Nothing would be posted.` (`NothingToPreview`) | Nothing would be posted, including when every line has `Qty. to Receive = 0`. `nextStep`: No receipt line has Qty. to Receive. Set quantities on the receipt lines. |');
        HelpBuilder.AppendLine('| `Warehouse Receipt Header identifier is missing. Pass it as the subject, or as one of: systemId, recordSystemId, id, receiptNo, no.` (`MissingParameter`) | No identifier in `subject` or the request JSON. |');
        HelpBuilder.AppendLine('| `Warehouse Receipt Header "{value}" was not found (from {subject or key}).` (`RecordNotFound`) | An identifier was given but matches no record; `parameter` and `received` name it. Every identifier supplied is tried. |');
        HelpBuilder.AppendLine('| `The identifiers in {a} and {b} point to different records.` (`ConflictingIdentifiers`) | Two identifiers were given that resolve to different records. |');
        HelpBuilder.AppendLine('| `"{value}" is not a valid GUID` / `integer` `(from {key}).` (`InvalidParameterFormat`) | A SystemId or entry number that cannot be read. |');
        HelpBuilder.AppendLine('| `Warehouse Receipt {No} has no lines to post.` (`NothingToPreview`) | The header has no lines. All-zero `Qty. to Receive` is the row above. `nextStep`: No receipt line has Qty. to Receive. Set quantities on the receipt lines. |');
        HelpBuilder.AppendLine('| `Posting preview failed and no entries were captured. The warehouse receipt cannot be posted in its current state.` | The preview run failed and Business Central returned no error text. Returned with no `code`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse.Receipt.Post` — commit the actual posting after preview looks correct.');
        HelpBuilder.AppendLine('- `Warehouse.Receipt.Create` — create the receipt before previewing it.');

        HelpText := HelpBuilder.ToText();
    end;
}
