namespace Origo.Bifrost.Warehouse;

codeunit 10078421 "Whse Receipt Create Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Warehouse.Receipt.Create - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Creates one Warehouse Receipt per source document supplied. Wraps BC''s `Get Source Doc. Inbound` (codeunit 5751) — each Sales Return Order, Purchase Order, or Inbound Transfer Order produces its own Warehouse Receipt Header at the source''s receiving location.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound (state change)  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Location Prerequisites');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('The source document''s receiving Location must have `Require Receive = true`. Otherwise BC produces posted documents directly from the source without going through a Warehouse Receipt.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Receiving location resolution:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Source type | Receiving location |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `SalesReturnOrder` | `Sales Header.Location Code` |');
        HelpBuilder.AppendLine('| `PurchaseOrder` | `Purchase Header.Location Code` |');
        HelpBuilder.AppendLine('| `TransferOrder` | `Transfer Header."Transfer-to Code"` |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Additional behaviour depending on the Location setup:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Location flags | Effect on Warehouse Receipt line |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `Require Receive = true`, `Require Put-away = false` | `Qty. to Receive` is populated from the source line. `Warehouse.Receipt.Post` can run immediately. |');
        HelpBuilder.AppendLine('| `Require Receive = true`, `Require Put-away = true` | After posting the receipt, a Warehouse Put-away is created automatically. The receipt itself still posts successfully on its own. |');
        HelpBuilder.AppendLine('| `Directed Put-away and Pick = true` (e.g. WMS bin-mandatory location) | Bin Code must be set on the Warehouse Receipt Line before posting. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Discovery — find receipt-required locations');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Use `Data.Records.Get` on `Location` (table 14) with `tableView = "WHERE(Require Receive=CONST(true))"` to enumerate the candidates. Inspect `RequirePutaway`, `DirectedPutawayandPick`, and `BinMandatory` on each row to anticipate downstream put-away or bin requirements.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Idempotency / Safety Notes');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- Not idempotent: each call inserts new Warehouse Receipt Headers from the relevant number series.');
        HelpBuilder.AppendLine('- Each source document creates a separate header (BC standard behaviour).');
        HelpBuilder.AppendLine('- Source documents that are already on an open Warehouse Receipt, have no quantity to receive, or have an active put-away will fail with `No Warehouse Receipt was created`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Parameter | Type | Required | Notes |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| `sourceDocuments` | array | **Yes** | One or more `{ sourceType, documentNo }` entries. |');
        HelpBuilder.AppendLine('| `sourceDocuments[].sourceType` | string | **Yes** | `SalesReturnOrder`, `PurchaseOrder`, or `TransferOrder` (case-insensitive). |');
        HelpBuilder.AppendLine('| `sourceDocuments[].documentNo` | code[20] | **Yes** | The source document''s `No.`. |');
        HelpBuilder.AppendLine('| `locationCode` | code[10] | No | If supplied, validates each source uses the same receiving location. Subject to write-restriction on `Warehouse Receipt Header."Location Code"`. |');
        HelpBuilder.AppendLine('| `assignedUserId` | code[50] | No | Applied to every created header after creation. |');
        HelpBuilder.AppendLine('| `postingDate` | date | No | `YYYY-MM-DD`. Omitted: the header posting date is unchanged. An invalid value is an error. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "locationCode": "GREEN",');
        HelpBuilder.AppendLine('  "assignedUserId": "ADMIN",');
        HelpBuilder.AppendLine('  "sourceDocuments": [');
        HelpBuilder.AppendLine('    { "sourceType": "PurchaseOrder", "documentNo": "PO-1001" },');
        HelpBuilder.AppendLine('    { "sourceType": "TransferOrder", "documentNo": "T-2001" }');
        HelpBuilder.AppendLine('  ]');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "noOfReceipts": 2,');
        HelpBuilder.AppendLine('  "receipts": [');
        HelpBuilder.AppendLine('    {');
        HelpBuilder.AppendLine('      "recordSystemId": "00000000-0000-0000-0000-000000000000",');
        HelpBuilder.AppendLine('      "no": "WR001001",');
        HelpBuilder.AppendLine('      "locationCode": "GREEN",');
        HelpBuilder.AppendLine('      "assignedUserId": "ADMIN",');
        HelpBuilder.AppendLine('      "sourceType": "PurchaseOrder",');
        HelpBuilder.AppendLine('      "sourceDocumentNo": "PO-1001",');
        HelpBuilder.AppendLine('      "linesCreated": 3');
        HelpBuilder.AppendLine('    }');
        HelpBuilder.AppendLine('  ]');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Posting Gate');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('None — creation does not post. The companion `Warehouse.Receipt.Post` requires the `BIFROST WhsePost ori` permission set.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Field Restrictions');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse Receipt Header."Location Code"` — providing `locationCode` while this field is write-restricted is denied.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Wording below is the exact text returned by the implementation (verified live).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `sourceDocuments is required and must contain at least one entry.` | Request missing the array or array empty. |');
        HelpBuilder.AppendLine('| `Source #{n} is missing sourceType or documentNo (both required).` | One of the entries lacks a value. |');
        HelpBuilder.AppendLine('| `Unsupported sourceType ''{value}''. Expected: SalesReturnOrder, PurchaseOrder, TransferOrder.` | Source type not recognised. |');
        HelpBuilder.AppendLine('| `Sales Header / Purchase Header / Transfer Header "{no}" was not found (from sourceDocuments.documentNo).` (`RecordNotFound`) | The source document does not exist. |');
        HelpBuilder.AppendLine('| `Purchase Order ''{no}'' is not Released. Release it before creating a Warehouse Receipt.` | Source must be Released first. (`Sales Return Order` / `Transfer Order` variants use the same wording.) |');
        HelpBuilder.AppendLine('| `... uses/receives at location ''{x}'' which does not match the requested locationCode ''{y}''.` | When `locationCode` filter is supplied. |');
        HelpBuilder.AppendLine('| `Location ''{x}'' (from/Transfer-to on ...) does not require receipt routing` | Location card has `Require Receive = false`. |');
        HelpBuilder.AppendLine('| `No Warehouse Receipt was created for {sourceType} ''{no}'' — already on an open receipt, no lines remain to receive, or put-away already started.` | Bundled cause: source is on an existing open WR, or has been fully received, or has an active put-away. (Returned even when the PO has been previously fully received via a posted WR.) |');
        HelpBuilder.AppendLine('| `Field {n} is restricted for write on table {t}.` | `Bifrost Field Access` blocks `locationCode`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## End-to-End Workflow');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Typical sequence to receive a Purchase Order via the warehouse:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. **Create the Purchase Order** — `Purchase.Document.Create` (or `Data.Records.Set` on `Purchase Header`).');
        HelpBuilder.AppendLine('2. **Add Purchase Lines at the receipt-required Location** — `Data.Records.Set` on table `39` (`Purchase Line`).');
        HelpBuilder.AppendLine('3. **Release the Purchase Order** — `Purchase.Document.Release`.');
        HelpBuilder.AppendLine('4. **Create the Warehouse Receipt** — `Warehouse.Receipt.Create` (this message type).');
        HelpBuilder.AppendLine('5. (Optional) Adjust `Qty. to Receive` on the Warehouse Receipt Lines via `Data.Records.Set` if partial receive is intended.');
        HelpBuilder.AppendLine('6. **Post the Warehouse Receipt** — `Warehouse.Receipt.Post`. This creates Posted Whse. Receipt and Posted Purchase Receipt records and increases inventory.');
        HelpBuilder.AppendLine('7. (Optional) Use `Warehouse.Receipt.Post.Preview` between steps 5 and 6 to see the predicted ledger entries without committing.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse.Receipt.Post` — post the created Warehouse Receipt.');
        HelpBuilder.AppendLine('- `Warehouse.Receipt.Post.Preview` — simulate the post and inspect captured ledger entries.');
        HelpBuilder.AppendLine('- `Warehouse.Shipment.Create` / `Warehouse.Shipment.Post` — outbound counterparts.');

        HelpText := HelpBuilder.ToText();
    end;
}
