namespace Origo.Bifrost.Warehouse;

codeunit 10078422 "Whse Receipt Post Help ori"
{
    Access = Internal;

    internal procedure GetHelpText() HelpText: Text
    var
        HelpBuilder: TextBuilder;
    begin
        HelpBuilder.AppendLine('# Warehouse.Receipt.Post - Help');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Overview');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Posts an existing Warehouse Receipt by running BC''s `Whse.-Post Receipt` (codeunit 5760). Creates a `Posted Whse. Receipt` plus the underlying posted source documents (Posted Purchase Receipt, Posted Return Shipment, or Posted Transfer Receipt) and increases inventory.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('**Direction**: Inbound (state change)  **Content-Type**: `text/json`');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Preconditions');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- The Warehouse Receipt Header must exist (typically created by `Warehouse.Receipt.Create`).');
        HelpBuilder.AppendLine('- At least one Warehouse Receipt Line with `Qty. to Receive > 0`.');
        HelpBuilder.AppendLine('- For Directed Put-away & Pick locations the line `Bin Code` must be set before posting.');
        HelpBuilder.AppendLine('- Unlike Warehouse Shipment, there is **no `invoice` flag** — receipts only do the receive. Vendor invoicing on the Purchase Order is a separate later action.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Identifier Resolution Order');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('1. `subject` field (GUID → `SystemId`, text → `No.`).');
        HelpBuilder.AppendLine('2. Request JSON `systemId` / `recordSystemId` / `id` (GUID).');
        HelpBuilder.AppendLine('3. Request JSON `receiptNo` / `no` (text).');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Idempotency / Safety Notes');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- **Not** idempotent at the message-type level: re-posting the same receipt produces an error from BC (lines already posted / receipt no longer exists).');
        HelpBuilder.AppendLine('- The Warehouse Receipt Header is consumed by the post — after success it is deleted, the response carries the `postedWhseReceiptNo` to follow up.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Request Parameters');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Parameter | Type | Required | Notes |');
        HelpBuilder.AppendLine('|---|---|---|---|');
        HelpBuilder.AppendLine('| `subject` | text/guid | One identifier required | Bifrost subject. GUID → SystemId lookup; text → `No.` lookup. |');
        HelpBuilder.AppendLine('| `systemId` / `recordSystemId` / `id` | guid | (alternative) | In request JSON. |');
        HelpBuilder.AppendLine('| `receiptNo` / `no` | code[20] | (alternative) | In request JSON. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('### Request Example');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{ "receiptNo": "WR001001" }');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Response Shape');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Verified live (Purchase Order receipt at GULUR, 5 × item 1896-S):');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('```json');
        HelpBuilder.AppendLine('{');
        HelpBuilder.AppendLine('  "status": "Success",');
        HelpBuilder.AppendLine('  "receiptNo": "RE000010",');
        HelpBuilder.AppendLine('  "postedWhseReceiptNo": "R_000005",');
        HelpBuilder.AppendLine('  "postedWhseReceiptSystemId": "AC903C2D-DF61-F111-B7A5-FCCA66B996D7",');
        HelpBuilder.AppendLine('  "postedDocuments": [');
        HelpBuilder.AppendLine('    {');
        HelpBuilder.AppendLine('      "postedSourceDocument": "Posted Receipt",');
        HelpBuilder.AppendLine('      "postedSourceNo": "107242",');
        HelpBuilder.AppendLine('      "sourceDocument": "Purchase Order",');
        HelpBuilder.AppendLine('      "sourceNo": "106031"');
        HelpBuilder.AppendLine('    }');
        HelpBuilder.AppendLine('  ]');
        HelpBuilder.AppendLine('}');
        HelpBuilder.AppendLine('```');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Number formats are example only — `postedWhseReceiptNo` is taken from the location''s `Whse. Receipt Nos.` series, `postedSourceNo` from the source document''s posting series (e.g. `P-RCPT` for Purchase Order). The `postedSourceDocument` enumeration is one of `Posted Receipt`, `Posted Return Shipment`, `Posted Transfer Receipt`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Posting Gate');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('Requires the `BIFROST WhsePost ori` permission set (always). No G/L gate — receipts do not write to G/L Register.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Field Restrictions');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('None enforced by this message type. Standard BC validation applies on the warehouse receipt lines.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Errors');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('| Error | Cause |');
        HelpBuilder.AppendLine('|---|---|');
        HelpBuilder.AppendLine('| `Warehouse Receipt Header identifier is missing. Pass it as the subject, or as one of: systemId, recordSystemId, id, receiptNo, no.` (`MissingParameter`) | No identifier in `subject` or the request JSON. |');
        HelpBuilder.AppendLine('| `Warehouse Receipt Header "{value}" was not found (from {subject or key}).` (`RecordNotFound`) | An identifier was given but matches no record; `parameter` and `received` name it. Every identifier supplied is tried. |');
        HelpBuilder.AppendLine('| `The identifiers in {a} and {b} point to different records.` (`ConflictingIdentifiers`) | Two identifiers were given that resolve to different records. |');
        HelpBuilder.AppendLine('| `"{value}" is not a valid GUID` / `integer` `(from {key}).` (`InvalidParameterFormat`) | A SystemId or entry number that cannot be read. |');
        HelpBuilder.AppendLine('| `Warehouse Receipt {No} has no lines to post.` | All lines have Qty. to Receive = 0 or header has no lines. |');
        HelpBuilder.AppendLine('| `The Warehouse Receipt Header does not exist. ...` | Re-posting the same receipt. After a successful post the header is deleted. |');
        HelpBuilder.AppendLine('| Any BC posting error (e.g. `Bin Code must have a value`) | Bubbled from `Whse.-Post Receipt`. |');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## End-to-End Workflow');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('See `Warehouse.Receipt.Create` for the full create → release → receive → post sequence. Typical follow-ups after a successful post:');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- Inspect `Posted Whse. Receipt` (table 7320) and `Posted Whse. Receipt Line` (table 7319) via `Data.Records.Get`.');
        HelpBuilder.AppendLine('- Inspect the resulting Posted Purchase Receipt / Posted Return Shipment / Posted Transfer Receipt via the `postedDocuments` array.');
        HelpBuilder.AppendLine('- Verify inventory via `Inventory.Item.GetInventory` or `Data.Records.Get` on `Item Ledger Entry`.');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('## Related Message Types');
        HelpBuilder.AppendLine('');
        HelpBuilder.AppendLine('- `Warehouse.Receipt.Create` — create the receipt being posted.');
        HelpBuilder.AppendLine('- `Warehouse.Receipt.Post.Preview` — simulate the post without committing.');
        HelpBuilder.AppendLine('- `Warehouse.Shipment.Post` — outbound counterpart.');

        HelpText := HelpBuilder.ToText();
    end;
}
